import type { Metadata } from "next";
import "./globals.scss";
import { JetBrains_Mono } from "next/font/google";

const JetBrains = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr" className={JetBrains.className}>
			<body>{children}</body>
		</html>
	);
}
